global:
  resolve_timeout: 1m
  slack_api_url: 'YOUR_SLACK_WEBHOOK_URL_HERE'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#dev'
    send_resolved: true
