version: "2.1"

services:
  jobmanager:
    image: flink-local
    build:
      context: resources/flex
      dockerfile: Dockerfile
    command: jobmanager
    container_name: jobmanager
    ports:
      - "8081:8081"
    networks:
      - factorhouse
    environment:
      - BOOTSTRAP_SERVERS=kafka-0:9092
      - RUNTIME_ENV=docker
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        state.backend: filesystem
        state.checkpoints.dir: file:///tmp/flink-checkpoints
        state.savepoints.dir: file:///tmp/flink-savepoints
        heartbeat.interval: 1000
        heartbeat.timeout: 5000
        rest.port: 8081
        rest.address: localhost
        rest.bind-address: 0.0.0.0
        rest.flamegraph.enabled: true
        web.backpressure.refresh-interval: 10000
    volumes:
      - ./flink-apps:/tmp/apps
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/config"]
      interval: 5s
      timeout: 5s
      retries: 5

  taskmanager-1:
    image: flink-local
    build:
      context: resources/flex
      dockerfile: Dockerfile
    command: taskmanager
    networks:
      - factorhouse
    depends_on:
      jobmanager:
        condition: service_healthy
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 10
        state.backend: filesystem
        state.checkpoints.dir: file:///tmp/flink-checkpoints
        state.savepoints.dir: file:///tmp/flink-savepoints
        heartbeat.interval: 1000
        heartbeat.timeout: 5000
    volumes:
      - ./flink-apps:/tmp/apps

  taskmanager-2:
    image: flink-local
    build:
      context: resources/flex
      dockerfile: Dockerfile
    command: taskmanager
    networks:
      - factorhouse
    depends_on:
      jobmanager:
        condition: service_healthy
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 10
        state.backend: filesystem
        state.checkpoints.dir: file:///tmp/flink-checkpoints
        state.savepoints.dir: file:///tmp/flink-savepoints
        heartbeat.interval: 1000
        heartbeat.timeout: 5000
    volumes:
      - ./flink-apps:/tmp/apps

  taskmanager-3:
    image: flink-local
    build:
      context: resources/flex
      dockerfile: Dockerfile
    command: taskmanager
    networks:
      - factorhouse
    depends_on:
      jobmanager:
        condition: service_healthy
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 10
        state.backend: filesystem
        state.checkpoints.dir: file:///tmp/flink-checkpoints
        state.savepoints.dir: file:///tmp/flink-savepoints
        heartbeat.interval: 1000
        heartbeat.timeout: 5000
    volumes:
      - ./flink-apps:/tmp/apps

  flex:
    image: factorhouse/flex:latest
    container_name: flex
    pull_policy: always
    restart: always
    ports:
      - "3000:3000"
    networks:
      - factorhouse
    depends_on:
      jobmanager:
        condition: service_healthy
    env_file:
      - resources/flex/local-trial.env
    mem_limit: 2G
    volumes:
      - ./resources/jaas:/etc/kpow/jaas
      - ./resources/rbac:/etc/kpow/rbac

networks:
  factorhouse:
    external: ${EXT_NET:-false}
    name: factorhouse-local
