scrape_configs:
  - job_name: 'kpow'
    metrics_path: '/metrics/v1'
    static_configs:
      - targets: ['kpow:3000']

rule_files:
  - kpow-rules.yml

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093
